# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2018 BayLibre, SAS
#
# Author: Neil Armstrong <narmstrong@baylibre.com>

obj-${CONFIG_VIDEO_MESON} = meson_vpu.o meson_vpu_init.o meson_canvas.o meson_plane.o meson_venc.o meson_vclk.o meson_dw_hdmi.o ../dw_hdmi.o
